imports:
    - { resource: services/routing.yml }
    - { resource: services/controller.yml }
    - { resource: services/installer.yml }
    - { resource: services/commands.yml }
    - { resource: services/validators.yml }
    - { resource: services/form.yml }

services:
    _defaults:
        public: true

    CoreShop\Component\Resource\Metadata\RegistryInterface: '@CoreShop\Component\Resource\Metadata\Registry'
    CoreShop\Component\Resource\Metadata\Registry: ~

    CoreShop\Bundle\ResourceBundle\Pimcore\ObjectManager: ~

    CoreShop\Bundle\ResourceBundle\Serialization\RelationsHandler:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: jms_serializer.handler, type: relation, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: relation, direction: deserialization, format: json, method: deserializeRelation}
            - { name: jms_serializer.handler, type: relation<?>, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: relation<?>, direction: deserialization, format: json, method: deserializeRelation}

    CoreShop\Bundle\ResourceBundle\Serialization\PimcoreObjectHandler:
        tags:
            - { name: jms_serializer.handler, type: pimcoreObject, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: pimcoreObject, direction: deserialization, format: json, method: deserializeRelation}
            - { name: jms_serializer.handler, type: pimcoreObject<?>, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: pimcoreObject<?>, direction: deserialization, format: json, method: deserializeRelation}

    CoreShop\Bundle\ResourceBundle\Serialization\PimcoreDocumentHandler:
        tags:
            - { name: jms_serializer.handler, type: pimcoreDocument, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: pimcoreDocument, direction: deserialization, format: json, method: deserializeRelation}
            - { name: jms_serializer.handler, type: pimcoreDocument<?>, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: pimcoreDocument<?>, direction: deserialization, format: json, method: deserializeRelation}

    CoreShop\Bundle\ResourceBundle\Serialization\PimcoreAssetHandler:
         tags:
             - { name: jms_serializer.handler, type: pimcoreAsset, direction: serialization, format: json, method: serializeRelation}
             - { name: jms_serializer.handler, type: pimcoreAsset, direction: deserialization, format: json, method: deserializeRelation}
             - { name: jms_serializer.handler, type: pimcoreAsset<?>, direction: serialization, format: json, method: serializeRelation}
             - { name: jms_serializer.handler, type: pimcoreAsset<?>, direction: deserialization, format: json, method: deserializeRelation}

    CoreShop\Bundle\ResourceBundle\Serialization\PimcoreSiteHandler:
        tags:
            - { name: jms_serializer.handler, type: pimcoreSite, direction: serialization, format: json, method: serializeRelation}
            - { name: jms_serializer.handler, type: pimcoreSite, direction: deserialization, format: json, method: deserializeRelation}

    CoreShop\Bundle\ResourceBundle\Serialization\CarbonHandler:
        tags:
            - { name: jms_serializer.handler, type: carbon, direction: serialization, format: json, method: serializeRelation }

    CoreShop\Bundle\ResourceBundle\Form\Extension\HttpFoundation\HttpFoundationRequestHandler:
        decorates: form.type_extension.form.request_handler
        decoration_priority: 256
        public: false

    CoreShop\Bundle\ResourceBundle\Controller\ResourceSettingsController:
        arguments:
            $viewHandler: '@CoreShop\Bundle\ResourceBundle\Controller\ViewHandler'
        tags:
            - { name: container.service_subscriber }

    CoreShop\Bundle\ResourceBundle\Form\Helper\ErrorSerializer:
        arguments:
            - '@translator'

    CoreShop\Bundle\ResourceBundle\Serialization\Driver\PimcoreDataObjectDriver:
        decorates: 'jms_serializer.metadata.annotation_driver'
        arguments:
            - '@CoreShop\Bundle\ResourceBundle\Serialization\Driver\PimcoreDataObjectDriver.inner'

    CoreShop\Bundle\ResourceBundle\EventListener\DeepCopySubscriber:
        tags:
            - { name: kernel.event_subscriber }

    CoreShop\Bundle\ResourceBundle\Serialization\VersionObjectConstructor:
        decorates: 'jms_serializer.object_constructor'
        arguments:
            - '@CoreShop\Bundle\ResourceBundle\Serialization\VersionObjectConstructor.inner'
            - '@jms_serializer.unserialize_object_constructor'

    CoreShop\Component\Resource\Service\FolderCreationServiceInterface: '@CoreShop\Component\Resource\Service\FolderCreationService'
    CoreShop\Component\Resource\Service\FolderCreationService:
        arguments:
            - '@CoreShop\Component\Resource\Metadata\RegistryInterface'
            - '@CoreShop\Component\Pimcore\DataObject\ObjectServiceInterface'

    CoreShop\Bundle\ResourceBundle\Pimcore\CacheResourceMarshaller: ~

    CoreShop\Bundle\ResourceBundle\Slug\ResourceConfigurationSlugGenerator:
        decorates: 'CoreShop\Component\Pimcore\Slug\DataObjectSlugGeneratorInterface'
        arguments:
            - '@CoreShop\Bundle\ResourceBundle\Slug\ResourceConfigurationSlugGenerator.inner'
            - '@CoreShop\Component\Resource\Metadata\RegistryInterface'

    CoreShop\Component\Resource\Pimcore\ResourceSlugLinkGenerator:
        decorates: 'CoreShop\Component\Pimcore\Slug\SluggableLinkGenerator'
        arguments:
            - '@CoreShop\Component\Resource\Pimcore\ResourceSlugLinkGenerator.inner'
            - '@CoreShop\Component\Resource\Metadata\RegistryInterface'