Pimcore\Model\DataObject\AbstractObject:
    exclusion_policy: ALL
    virtual_properties:
        getId:
            expose: true
            type: integer
            xml_attribute: true
            serialized_name: id
        creationDate:
            exp: object.getCreationDate()
            type: carbon
            xml_attribute: true
            serialized_name: creationDate
        modificationDate:
            exp: object.getModificationDate()
            type: carbon
            xml_attribute: true
            serialized_name: modificationDate